# author: Mihir Pednekar
# student id : 19027656

# define C compiler
CC = g++

# define any compile-time flags
CFLAGS = -Wall -c

#remove files
RM = rm -rf

# define the executable file 
MAIN = main

all:    $(MAIN)

$(MAIN): main.o
	$(CC) main.o -o $(MAIN)

main.o: main.cpp
	$(CC) $(CFLAGS) main.cpp

clean:
	$(RM) *.o $(MAIN)
